baseurl = ""
title = "emsal"
theme = "whiteplain"
languageCode = "en"
# google analytics tracking id
# googleAnalytics = "Toracking ID"

# Copyright notice. This is displayer in the footer.
# copyright = "&copy; Copyright 2017 Your name"

[params]
  # whether to use CDN or local file for fontawesome
  #useCDN = false
  # whether to include external sharing scripts and icons for twitter, facebook and co.
  #showShareIcons = false
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "emsal"
  gravatar = "emsal1863@gmail.com"
  github = "emsal0"
  email = "em@emsal.me"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  post = "/:year/:month/:slug/"

[markup]
  [markup.blackFriday]
    skipHTML = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4

# Header Menu
# [[menu.main]]
#   name = "Tags"
#   identifier = "tags"
#   url = "/tags/"
#   weight = 2
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 3

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"

